spring:
  data:
    mongodb:
      host: mongodb
      database: admin
      authentication-database: admin

  keycloak:
      server-url: http://keycloak-server:8080
  security:
    oauth2:
      resourceserver:  
        jwt:
          issuer-uri: https://keycloak.greeta.net/realms/erp-realm
          jwk-set-uri: ${spring.keycloak.server-url}/realms/erp-realm/protocol/openid-connect/certs

server:
  forward-headers-strategy: framework

jwt:
  auth:
    converter:
      resource-id: erp-app
      principal-attribute: preferred_username

openapi:
  oauthflow:
    authServerUrl: https://keycloak.greeta.net
    realm: erp-realm

erp-app:
  base-url: https://erp.greeta.net
  redirect-url: ${erp-app.base-url}/*

movie-app:
  base-url: https://movie.greeta.net
  redirect-url: ${movie-app.base-url}/*    