spring:
  application:
    name: gateway
  config:
    import: configtree:/workspace/secrets/*/
  cloud:
    bootstrap:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://movie.greeta.net"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee
          uri: http://employee:8080
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: department
          uri: http://department:8080
          predicates:
            - Path=/department/**
          filters:
            - RewritePath=/department/(?<path>.*), /$\{path}
        - id: organization
          uri: http://organization:8080
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: movie
          uri: http://movie:8080
          predicates:
            - Path=/movie/**
          filters:
            - RewritePath=/movie/(?<path>.*), /$\{path}
  keycloak:
      server-url: http://keycloak-server:8080

  redis:
    connect-timeout: 2s
    host: gateway-redis
    port: 6379
    timeout: 1s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: erp:gateway
  security:
    oauth2: 
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.greeta.net/realms/erp-realm
          jwk-set-uri: ${spring.keycloak.server-url}/realms/erp-realm/protocol/openid-connect/certs
       

jwt:
  auth:
    converter:
      resource-id: erp-app
      principal-attribute: preferred_username

erp-app:
  base-url: https://erp.greeta.net
  redirect-url: ${erp-app.base-url}/*

movie-app:
  base-url: https://movie.greeta.net
  redirect-url: ${movie-app.base-url}/*

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


server.forward-headers-strategy: framework

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /department/v3/api-docs
        name: Department Service
        primaryName: Department Service
      - url: /employee/v3/api-docs
        name: Employee Service
        primaryName: Employee Service
      - url: /organization/v3/api-docs
        name: Organization Service
        primaryName: Organization Service
      - url: /movie/v3/api-docs
        name: Movie Service
        primaryName: Movie Service